apiVersion: v1
kind: ReplicationController
metadata:
 name: httpd-replicationcontroller
spec:
 replicas: 3
 selector:
   app: httpd_app
   type: front_end
 template:
   metadata:
    labels:
      app: httpd_app
      type: front_end
   spec:
     containers:
       - name: httpd-container
         image: httpd:latest