apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  type: NodePort
  ports:
    - port: 5001
      nodePort: 31001
      targetPort: 80
      name: http
  selector:
    app: result-deployment
