apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
     app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
     app: voting-app
  template:
    metadata:
     labels:
      app: voting-app
    spec:
      containers:
       - name: vote
         image: kodekloud/examplevotingapp_vote:before
         ports:
           - containerPort: 80
