apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
  matchLabels:
   app: worker
  template:
   metadata:
    labels:
      app: worker
   spec:
     containers:
      - name: worker
        image: “kodekloud/examplevotingapp_worker”
