apiVersion: v1
kind: Service
metadata:
  name: grafana-service-devops
spec: 
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
  type: NodePort